import React from "react";
import HeaderMenuItem from "components/headerMenuItem";
import { useRouter } from "next/router";

const TemplateMenu = () => {
  const router = useRouter();
  return (
    <div className="max-h-full overflow-y-auto">
      <h6 className="mt-2 px-2">Components</h6>
      <HeaderMenuItem
        text={"alert"}
        href="/template/alert"
        active={/\/alert/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"calendar"}
        href="/template/calendar"
        active={/\/calendar/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"card"}
        href="/template/card"
        active={/\/card/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"carousel"}
        href="/template/carousel"
        active={/\/carousel/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"checkbox"}
        href="/template/checkbox"
        active={/\/checkbox/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"chip"}
        href="/template/chip"
        active={/\/chip/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"datePicker"}
        href="/template/datePicker"
        active={/\/datePicker/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"dateRangePicker"}
        href="/template/dateRangePicker"
        active={/\/dateRangePicker/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"fileUploader"}
        href="/template/fileUploader"
        active={/\/fileUploader/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"gantt"}
        href="/template/gantt"
        active={/\/gantt/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"introGuide"}
        href="/template/introGuide"
        active={/\/introGuide/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"listItem"}
        href="/template/listItem"
        active={/\/listItem/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"logger"}
        href="/template/logger"
        active={/\/logger/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"mediaLibrary"}
        href="/template/mediaLibrary"
        active={/\/mediaLibrary/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"modal"}
        href="/template/modal"
        active={/\/modal/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"radioButton"}
        href="/template/radioButton"
        active={/\/radioButton/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"switch"}
        href="/template/switch"
        active={/\/switch/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"table"}
        href="/template/table"
        active={/\/table/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"textInput"}
        href="/template/textInput"
        active={/\/textInput/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"timePicker"}
        href="/template/timePicker"
        active={/\/timePicker/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"toast"}
        href="/template/toast"
        active={/\/toast/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"tooltip"}
        href="/template/tooltip"
        active={/\/tooltip/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"typography"}
        href="/template/typography"
        active={/\/typography/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"Dropdown"}
        href="/template/dropdown"
        active={/\/typography/.test(router.asPath)}
      />
      <h6 className="mt-2 px-2">Compositions</h6>
      <HeaderMenuItem
        text={"dashboard"}
        href="/template/dashboard"
        active={/\/dashboard/.test(router.asPath)}
        disabled
      />
      <HeaderMenuItem
        text={"mail"}
        href="/template/mail"
        active={/\/mail/.test(router.asPath)}
        disabled
      />
      <HeaderMenuItem
        text={"messenger"}
        href="/template/compositions/messenger"
        active={/\/messenger/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"profile"}
        href="/template/compositions/profile"
        active={/\/profile/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"settings"}
        href="/template/settings"
        active={/\/settings/.test(router.asPath)}
        disabled
      />
      <HeaderMenuItem
        text={"shopping-cart"}
        href="/template/compositions/shopping-cart"
        active={/\/shopping-cart/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"stripe-cards"}
        href="/template/compositions/stripe/cards"
        active={/\/stripe\/cards/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"stripe-checkout"}
        href="/template/compositions/stripe/checkout"
        active={/\/stripe\/checkout$/.test(router.asPath)}
      />
      <HeaderMenuItem
        text={"stripe-checkout-redirect"}
        href="/template/compositions/stripe/checkout-redirect"
        active={/\/stripe\/checkout-redirect/.test(router.asPath)}
      />
    </div>
  );
};

export default TemplateMenu;
