trigger:
  - production

variables:
  # STEP 1: Define api name in cloud
  api-name: blueprint720-api
  api-image-name: "$(acrname).azurecr.io/$(api-name):$(build.buildId)"

jobs:
  - job: Api_Production
    steps:
      - task: DownloadSecureFile@1
        name: mySecureFile
        displayName: "download env file"
        inputs:
          secureFile: .env.production
      - task: CopyFiles@2
        displayName: "copy env file"
        inputs:
          SourceFolder: $(Agent.TempDirectory)
          Contents: '**\.env.production'
          TargetFolder: $(Build.SourcesDirectory)
      - script: mv .env.production .env
        displayName: "renaming env file"
      - script: echo "$(appPassword)" | docker login -u $(appId) --password-stdin $(acrname).azurecr.io
        displayName: "docker login"
      - script: docker build --build-arg env=production -f ./Dockerfile -t $(api-image-name) .
        displayName: "docker build api"
      - script: docker push $(api-image-name)
        displayName: "docker push api"

  - job: Publish_Artifacts
    steps:
      - bash: find ./pipelines/production/resource-manifests -type f -name "*.yaml" -print0 | xargs -0 sed -i -e "s/{{TAG}}/$(build.buildId)/" -e "s/{{DOCKER_USER}}/$(acrname).azurecr.io/"
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(System.DefaultWorkingDirectory)/pipelines/production/resource-manifests"
          artifactName: resource-manifests
