apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint720-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueprint720-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: blueprint720-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: blueprint720-api
        image: {{image}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
      imagePullSecrets:
      - name: dockerhubcert
---
apiVersion: v1
kind: Service
metadata:
  name: blueprint720-api-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: blueprint720-api