version: "3.7"

services:
  api:
    container_name: wedding-api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb
      - PORT=8080
    networks:
      - wedding-net
    depends_on:
      - mongodb
  mongodb:
    container_name: wedding-mongodb
    image: mongo:3.6.18-xenial
    ports:
      - 27018:27017
    networks:
      - wedding-net
networks:
  wedding-net:
