version: "3.7"

services:
  web:
    container_name: full-stack-web
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API=api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - full-stack-net
    depends_on:
      - api

networks:
  full-stack-net:
